"""
Django settings for mysite project.

Generated by 'django-admin startproject' using Django 3.0.dev20190522053454.

For more information on this file, see
https://docs.djangoproject.com/en/dev/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/dev/ref/settings/
"""

import os
from mongoengine import connect

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/dev/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '!4xujev##dzch7)4f&w!19ps(#*=c+2=*o0y)p3_!7r4x!(14%'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'mongo_auth'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'mysite.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'mysite.wsgi.application'


# Database
# https://docs.djangoproject.com/en/dev/ref/settings/#databases

# DATABASES = {
# 'default':{
#     'ENGINE':'djongo',
#     'NAME': 'djongo',
#     'HOST':'mongodb://admin:admin@cluster0-shard-00-00-vc0t1.mongodb.net:27017,cluster0-shard-00-01-vc0t1.mongodb.net:27017,cluster0-shard-00-02-vc0t1.mongodb.net:27017/test?ssl=true&replicaSet=Cluster0-shard-0&authSource=admin&retryWrites=true',
#     'USER':'admin',
#     'PASSWORD':'admin'
# }

# }

MONGO_DATABASE_NAME = 'djongo'
MONGO_HOST = 'mongodb://admin:admin@cluster0-shard-00-00-vc0t1.mongodb.net:27017,cluster0-shard-00-01-vc0t1.mongodb.net:27017,cluster0-shard-00-02-vc0t1.mongodb.net:27017/djongo?ssl=true&replicaSet=Cluster0-shard-0&authSource=admin&retryWrites=true'
#MONGO_HOST='cluster0-shard-00-02-vc0t1.mongodb.net/test?ssl=true&replicaSet=Cluster0-shard-0&authSource=admin&retryWrites=true'
connect(MONGO_DATABASE_NAME, host=MONGO_HOST)

MANGO_JWT_SETTINGS = {
    "db_host": 'cluster0-shard-00-00-vc0t1.mongodb.net:27017,cluster0-shard-00-01-vc0t1.mongodb.net:27017,cluster0-shard-00-02-vc0t1.mongodb.net:27017/test?ssl=true&replicaSet=Cluster0-shard-0&authSource=admin&retryWrites=true',
    "db_port": "27017",
    "db_name": "djongo",
    "db_user": "admin",
    "db_pass": "admin"
}

# Password validation
# https://docs.djangoproject.com/en/dev/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/dev/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/dev/howto/static-files/

STATIC_URL = '/static/'
